export var countries = [
    {"code":  "阿富汗 | Afghanistan", "value": "阿富汗 | Afghanistan" }, 
    {"text":  "奥兰群岛 | Åland Islands","value": "奥兰群岛 | Åland Islands"}, 
    {"text":  "阿尔巴尼亚 | Albania","value": "阿尔巴尼亚 | Albania"}, 
    {"text":  "阿尔及利亚 | Algeria","value": "阿尔及利亚 | Algeria"}, 
    {"text":  "美属萨摩亚 | American Samoa","value": "美属萨摩亚 | American Samoa"}, 
    {"text":  "安道尔 | Andorra","value": "安道尔 | Andorra"}, 
    {"text":  "Angola | Angola","value": "Angola | Angola"}, 
    {"text":  "安圭拉 | Anguilla","value": "安圭拉 | Anguilla"}, 
    {"text":  "Antarctica","value": "Antarctica"}, 
    {"text":  "安提瓜和巴布达 | Antigua and Barbuda","value": "安提瓜和巴布达 | Antigua and Barbuda"}, 
    {"text":  "阿根廷 | Argentina","value": "阿根廷 | Argentina"}, 
    {"text":  "亚美尼亚 | Armenia","value": "亚美尼亚 | Armenia"}, 
    {"text":  "阿鲁巴 | Aruba","value": "阿鲁巴 | Aruba"}, 
    {"text":  "科科斯（基林）群岛 | Australia","value": "科科斯（基林）群岛 | Australia"}, 
    {"text":  "奥地利 | Austria","value": "奥地利 | Austria"}, 
    {"text":  "阿塞拜疆 | Azerbaijan","value": "阿塞拜疆 | Azerbaijan"}, 
    {"text":  "巴哈马 | Bahamas","value": "巴哈马 | Bahamas"}, 
    {"text":  "巴林 | Bahrain","value": "巴林 | Bahrain"}, 
    {"text":  "孟加拉国 | Bangladesh","value": "孟加拉国 | Bangladesh"}, 
    {"text":  "巴巴多斯 | Barbados","value": "巴巴多斯 | Barbados"}, 
    {"text":  "白俄罗斯 | Belarus","value": "白俄罗斯 | Belarus"}, 
    {"text":  "比利时 | Belgium","value": "比利时 | Belgium"}, 
    {"text":  "伯利兹 | Belize","value": "伯利兹 | Belize"}, 
    {"text":  "贝宁 | Benin","value": "贝宁 | Benin"}, 
    {"text":  "百慕大 | Bermuda","value": "百慕大 | Bermuda"}, 
    {"text":  "不丹 | Bhutan","value": "不丹 | Bhutan"}, 
    {"text":  "玻利维亚 | Bolivia","value": "玻利维亚 | Bolivia"}, 
    {"text":  "波斯尼亚和黑塞哥维那 | Bosnia and Herzegovina","value": "波斯尼亚和黑塞哥维那 | Bosnia and Herzegovina"}, 
    {"text":  "博茨瓦纳 | Botswana","value": "博茨瓦纳 | Botswana"}, 
    {"text":  "Bouvet Island","value": "Bouvet Island"}, 
    {"text":  "巴西 | Brazil","value": "巴西 | Brazil"}, 
    {"text":  "英属印度洋领地 | British Indian Ocean Territory","value": "英属印度洋领地 | British Indian Ocean Territory"}, 
    {"text":  "文莱 | Brunei Darussalam","value": "文莱 | Brunei Darussalam"}, 
    {"text":  "保加利亚 | Bulgaria","value": "保加利亚 | Bulgaria"}, 
    {"text":  "布基纳法索 | Burkina Faso","value": "布基纳法索 | Burkina Faso"}, 
    {"text":  "布隆迪 | Burundi","value": "布隆迪 | Burundi"}, 
    {"text":  "柬埔寨 | Cambodia","value": "柬埔寨 | Cambodia"}, 
    {"text":  "喀麦隆 | Cameroon","value": "喀麦隆 | Cameroon"}, 
    {"text":  "卡塔尔 | Canada","value": "卡塔尔 | Canada"}, 
    {"text":  "佛得角 | Cape Verde","value": "佛得角 | Cape Verde"}, 
    {"text":  "开曼群岛 | Cayman Islands","value": "开曼群岛 | Cayman Islands"}, 
    {"text":  "中非共和国 | Central African Republic","value": "中非共和国 | Central African Republic"}, 
    {"text":  "乍得 | Chad","value": "乍得 | Chad"}, 
    {"text":  "智利 | Chile","value": "智利 | Chile"}, 
    {"text":  "中国 | China","value": "中国 | China"}, 
    {"text":  "科科斯（基林）群岛 | 科科斯（基林）群岛 | Christmas Island","value": "科科斯（基林）群岛 | 科科斯（基林）群岛 | Christmas Island"}, 
    {"text":  "Cocos (Keeling) Islands","value": "Cocos (Keeling) Islands"}, 
    {"text":  "哥伦比亚 | Colombia","value": "哥伦比亚 | Colombia"}, 
    {"text":  "科摩罗 | Comoros","value": "科摩罗 | Comoros"}, 
    {"text":  "刚果 - 布拉柴维尔 | Congo","value": "刚果 - 布拉柴维尔 | Congo"}, 
    {"text":  "刚果民主共和国 | Congo, The Democratic Republic of the","value": "刚果民主共和国 | Congo, The Democratic Republic of the"}, 
    {"text":  "库克群岛 | Cook Islands","value": "库克群岛 | Cook Islands"}, 
    {"text":  "哥斯达黎加 | Costa Rica","value": "哥斯达黎加 | Costa Rica"}, 
    {"text":  "象牙海岸 | Cote D\"Ivoire","value": "象牙海岸 | Cote D\"Ivoire"}, 
    {"text":  "克罗地亚 | Croatia","value": "克罗地亚 | Croatia"}, 
    {"text":  "古巴 | Cuba","value": "古巴 | Cuba"}, 
    {"text":  "塞浦路斯 | Cyprus","value": "塞浦路斯 | Cyprus"}, 
    {"text":  "捷克共和国 | Czech Republic","value": "捷克共和国 | Czech Republic"}, 
    {"text":  "丹麦 | Denmark","value": "丹麦 | Denmark"}, 
    {"text":  "吉布提 | Djibouti","value": "吉布提 | Djibouti"}, 
    {"text":  "多米尼加 | Dominica","value": "多米尼加 | Dominica"}, 
    {"text":  "卡塔尔 | Dominican Republic","value": "卡塔尔 | Dominican Republic"}, 
    {"text":  "厄瓜多尔 | Ecuador","value": "厄瓜多尔 | Ecuador"}, 
    {"text":  "埃及 | Egypt","value": "埃及 | Egypt"}, 
    {"text":  "萨尔瓦多 | El Salvador","value": "萨尔瓦多 | El Salvador"}, 
    {"text":  "赤道几内亚 | Equatorial Guinea","value": "赤道几内亚 | Equatorial Guinea"}, 
    {"text":  "厄立特里亚 | Eritrea","value": "厄立特里亚 | Eritrea"}, 
    {"text":  "爱沙尼亚 | Estonia","value": "爱沙尼亚 | Estonia"}, 
    {"text":  "埃塞俄比亚 | Ethiopia","value": "埃塞俄比亚 | Ethiopia"}, 
    {"text":  "福克兰群岛 | Falkland Islands (Malvinas)","value": "福克兰群岛 | Falkland Islands (Malvinas)"}, 
    {"text":  "法罗群岛 | Faroe Islands","value": "法罗群岛 | Faroe Islands"}, 
    {"text":  "斐济 | Fiji","value": "斐济 | Fiji"}, 
    {"text":  "奥兰群岛 | Finland","value": "奥兰群岛 | Finland"}, 
    {"text":  "法国 | France","value": "法国 | France"}, 
    {"text":  "法属圭亚那 | French Guiana","value": "法属圭亚那 | French Guiana"}, 
    {"text":  "法属波利尼西亚 | French Polynesia","value": "法属波利尼西亚 | French Polynesia"}, 
    {"text":  "French Southern Territories","value": "French Southern Territories"}, 
    {"text":  "加蓬 | Gabon","value": "加蓬 | Gabon"}, 
    {"text":  "冈比亚 | Gambia","value": "冈比亚 | Gambia"}, 
    {"text":  "格鲁吉亚 | Georgia","value": "格鲁吉亚 | Georgia"}, 
    {"text":  "德国 | Germany","value": "德国 | Germany"}, 
    {"text":  "加纳 | Ghana","value": "加纳 | Ghana"}, 
    {"text":  "直布罗陀 | Gibraltar","value": "直布罗陀 | Gibraltar"}, 
    {"text":  "希腊 | Greece","value": "希腊 | Greece"}, 
    {"text":  "格陵兰岛 | Greenland","value": "格陵兰岛 | Greenland"}, 
    {"text":  "格林纳达 | Grenada","value": "格林纳达 | Grenada"}, 
    {"text":  "圣马丁 | Guadeloupe","value": "圣马丁 | Guadeloupe"}, 
    {"text":  "关岛 | Guam","value": "关岛 | Guam"}, 
    {"text":  "危地马拉 | Guatemala","value": "危地马拉 | Guatemala"}, 
    {"text":  "英国 | Guernsey","value": "英国 | Guernsey"}, 
    {"text":  "几内亚 | Guinea","value": "几内亚 | Guinea"}, 
    {"text":  "几内亚比绍 | Guinea-Bissau","value": "几内亚比绍 | Guinea-Bissau"}, 
    {"text":  "圭亚那 | Guyana","value": "圭亚那 | Guyana"}, 
    {"text":  "海地 | Haiti","value": "海地 | Haiti"}, 
    {"text":  "Heard Island and Mcdonald Islands","value": "Heard Island and Mcdonald Islands"}, 
    {"text":  "梵蒂冈 | Holy See (Vatican City State)","value": "梵蒂冈 | Holy See (Vatican City State)"}, 
    {"text":  "洪都拉斯 | Honduras","value": "洪都拉斯 | Honduras"}, 
    {"text":  "香港 | Hong Kong","value": "香港 | Hong Kong"}, 
    {"text":  "匈牙利 | Hungary","value": "匈牙利 | Hungary"}, 
    {"text":  "冰岛 | Iceland","value": "冰岛 | Iceland"}, 
    {"text":  "印度 | India","value": "印度 | India"}, 
    {"text":  "印度尼西亚 | Indonesia","value": "印度尼西亚 | Indonesia"}, 
    {"text":  "伊朗 | Iran, Islamic Republic Of","value": "伊朗 | Iran, Islamic Republic Of"}, 
    {"text":  "伊拉克 | Iraq","value": "伊拉克 | Iraq"}, 
    {"text":  "爱尔兰 | Ireland","value": "爱尔兰 | Ireland"}, 
    {"text":  "英国 | Isle of Man","value": "英国 | Isle of Man"}, 
    {"text":  "以色列 | Israel","value": "以色列 | Israel"}, 
    {"text":  "梵蒂冈 | Italy","value": "梵蒂冈 | Italy"}, 
    {"text":  "牙买加 | Jamaica","value": "牙买加 | Jamaica"}, 
    {"text":  "日本 | Japan","value": "日本 | Japan"}, 
    {"text":  "英国 | Jersey","value": "英国 | Jersey"}, 
    {"text":  "约旦 | Jordan","value": "约旦 | Jordan"}, 
    {"text":  "俄罗斯 | Kazakhstan","value": "俄罗斯 | Kazakhstan"}, 
    {"text":  "肯尼亚 | Kenya","value": "肯尼亚 | Kenya"}, 
    {"text":  "基里巴斯 | Kiribati","value": "基里巴斯 | Kiribati"}, 
    {"text":  "朝鲜 | Korea, Democratic People\"S Republic of","value": "朝鲜 | Korea, Democratic People\"S Republic of"}, 
    {"text":  "韩国 | Korea, Republic of","value": "韩国 | Korea, Republic of"}, 
    {"text":  "科威特 | Kuwait","value": "科威特 | Kuwait"}, 
    {"text":  "吉尔吉斯斯坦 | Kyrgyzstan","value": "吉尔吉斯斯坦 | Kyrgyzstan"}, 
    {"text":  "老挝 | Lao People\"S Democratic Republic","value": "老挝 | Lao People\"S Democratic Republic"}, 
    {"text":  "拉脱维亚 | Latvia","value": "拉脱维亚 | Latvia"}, 
    {"text":  "黎巴嫩 | Lebanon","value": "黎巴嫩 | Lebanon"}, 
    {"text":  "莱索托 | Lesotho","value": "莱索托 | Lesotho"}, 
    {"text":  "利比里亚 | Liberia","value": "利比里亚 | Liberia"}, 
    {"text":  "利比亚 | Libyan Arab Jamahiriya","value": "利比亚 | Libyan Arab Jamahiriya"}, 
    {"text":  "列支敦士登 | Liechtenstein","value": "列支敦士登 | Liechtenstein"}, 
    {"text":  "立陶宛 | Lithuania","value": "立陶宛 | Lithuania"}, 
    {"text":  "卢森堡 | Luxembourg","value": "卢森堡 | Luxembourg"}, 
    {"text":  "澳门 | Macao","value": "澳门 | Macao"}, 
    {"text":  "马其顿 | Macedonia, The Former Yugoslav Republic of","value": "马其顿 | Macedonia, The Former Yugoslav Republic of"}, 
    {"text":  "马达加斯加 | Madagascar","value": "马达加斯加 | Madagascar"}, 
    {"text":  "马拉维 | Malawi","value": "马拉维 | Malawi"}, 
    {"text":  "马来西亚 | Malaysia","value": "马来西亚 | Malaysia"}, 
    {"text":  "马尔代夫 | Maldives","value": "马尔代夫 | Maldives"}, 
    {"text":  "马里 | Mali","value": "马里 | Mali"}, 
    {"text":  "马耳他 | Malta","value": "马耳他 | Malta"}, 
    {"text":  "马绍尔群岛 | Marshall Islands","value": "马绍尔群岛 | Marshall Islands"}, 
    {"text":  "马提尼克 | Martinique","value": "马提尼克 | Martinique"}, 
    {"text":  "毛里塔尼亚 | Mauritania","value": "毛里塔尼亚 | Mauritania"}, 
    {"text":  "毛里求斯 | Mauritius","value": "毛里求斯 | Mauritius"}, 
    {"text":  "留尼汪岛 | Mayotte","value": "留尼汪岛 | Mayotte"}, 
    {"text":  "墨西哥 | Mexico","value": "墨西哥 | Mexico"}, 
    {"text":  "密克罗尼西亚 | Micronesia, Federated States of","value": "密克罗尼西亚 | Micronesia, Federated States of"}, 
    {"text":  "摩尔多瓦 | Moldova, Republic of","value": "摩尔多瓦 | Moldova, Republic of"}, 
    {"text":  "摩纳哥 | Monaco","value": "摩纳哥 | Monaco"}, 
    {"text":  "蒙古 | Mongolia","value": "蒙古 | Mongolia"}, 
    {"text":  "蒙特塞拉特 | Montserrat","value": "蒙特塞拉特 | Montserrat"}, 
    {"text":  "撒哈拉沙漠西部 | Morocco","value": "撒哈拉沙漠西部 | Morocco"}, 
    {"text":  "莫桑比克 | Mozambique","value": "莫桑比克 | Mozambique"}, 
    {"text":  "缅甸 | Myanmar","value": "缅甸 | Myanmar"}, 
    {"text":  "纳米比亚 | Namibia","value": "纳米比亚 | Namibia"}, 
    {"text":  "瑙鲁 | Nauru","value": "瑙鲁 | Nauru"}, 
    {"text":  "尼泊尔 | Nepal","value": "尼泊尔 | Nepal"}, 
    {"text":  "荷兰 | Netherlands","value": "荷兰 | Netherlands"}, 
    {"text":  "Netherlands Antilles","value": "Netherlands Antilles"}, 
    {"text":  "新喀里多尼亚 | New Caledonia","value": "新喀里多尼亚 | New Caledonia"}, 
    {"text":  "新西兰 | New Zealand","value": "新西兰 | New Zealand"}, 
    {"text":  "尼加拉瓜 | Nicaragua","value": "尼加拉瓜 | Nicaragua"}, 
    {"text":  "尼日尔 | Niger","value": "尼日尔 | Niger"}, 
    {"text":  "尼日利亚 | Nigeria","value": "尼日利亚 | Nigeria"}, 
    {"text":  "纽埃 | Niue","value": "纽埃 | Niue"}, 
    {"text":  "诺福克岛 | Norfolk Island","value": "诺福克岛 | Norfolk Island"}, 
    {"text":  "北马里亚纳群岛 | Northern Mariana Islands","value": "北马里亚纳群岛 | Northern Mariana Islands"}, 
    {"text":  "斯瓦尔巴和扬马延 | Norway","value": "斯瓦尔巴和扬马延 | Norway"}, 
    {"text":  "阿曼 | Oman","value": "阿曼 | Oman"}, 
    {"text":  "巴基斯坦 | Pakistan","value": "巴基斯坦 | Pakistan"}, 
    {"text":  "帕劳 | Palau","value": "帕劳 | Palau"}, 
    {"text":  "巴勒斯坦 | Palestinian Territory, Occupied","value": "巴勒斯坦 | Palestinian Territory, Occupied"}, 
    {"text":  "巴拿马 | Panama","value": "巴拿马 | Panama"}, 
    {"text":  "巴布亚新几内亚 | Papua New Guinea","value": "巴布亚新几内亚 | Papua New Guinea"}, 
    {"text":  "巴拉圭 | Paraguay","value": "巴拉圭 | Paraguay"}, 
    {"text":  "秘鲁 | Peru","value": "秘鲁 | Peru"}, 
    {"text":  "菲律宾 | Philippines","value": "菲律宾 | Philippines"}, 
    {"text":  "Pitcairn","value": "Pitcairn"}, 
    {"text":  "波兰 | Poland","value": "波兰 | Poland"}, 
    {"text":  "葡萄牙 | Portugal","value": "葡萄牙 | Portugal"}, 
    {"text":  "卡塔尔 | Puerto Rico","value": "卡塔尔 | Puerto Rico"}, 
    {"text":  " | Qatar","value": " | Qatar"}, 
    {"text":  "留尼汪岛 | Reunion","value": "留尼汪岛 | Reunion"}, 
    {"text":  "罗马尼亚 | Romania","value": "罗马尼亚 | Romania"}, 
    {"text":  "俄罗斯 | Russian Federation","value": "俄罗斯 | Russian Federation"}, 
    {"text":  "卢旺达 | RWANDA","value": "卢旺达 | RWANDA"}, 
    {"text":  "圣赫勒拿岛 | Saint Helena","value": "圣赫勒拿岛 | Saint Helena"}, 
    {"text":  "圣基茨和尼维斯 | Saint Kitts and Nevis","value": "圣基茨和尼维斯 | Saint Kitts and Nevis"}, 
    {"text":  "圣卢西亚 | Saint Lucia","value": "圣卢西亚 | Saint Lucia"}, 
    {"text":  "圣皮埃尔和密克隆 | Saint Pierre and Miquelon","value": "圣皮埃尔和密克隆 | Saint Pierre and Miquelon"}, 
    {"text":  "圣文森特和格林纳丁斯 | Saint Vincent and the Grenadines","value": "圣文森特和格林纳丁斯 | Saint Vincent and the Grenadines"}, 
    {"text":  "萨摩亚 | Samoa","value": "萨摩亚 | Samoa"}, 
    {"text":  "圣马力诺 | San Marino","value": "圣马力诺 | San Marino"}, 
    {"text":  "圣多美和普林西比 | Sao Tome and Principe","value": "圣多美和普林西比 | Sao Tome and Principe"}, 
    {"text":  "沙特阿拉伯‎) | Saudi Arabia","value": "沙特阿拉伯‎) | Saudi Arabia"}, 
    {"text":  "塞内加尔 | Senegal","value": "塞内加尔 | Senegal"}, 
    {"text":  "塞尔维亚 | Serbia","value": "塞尔维亚 | Serbia"}, 
    {"text":  "黑山 | Montenegro","value": "黑山 | Montenegro"}, 
    {"text":  "塞舌尔 | Seychelles","value": "塞舌尔 | Seychelles"}, 
    {"text":  "塞拉利昂 | Sierra Leone","value": "塞拉利昂 | Sierra Leone"}, 
    {"text":  "新加坡 | Singapore","value": "新加坡 | Singapore"}, 
    {"text":  "斯洛伐克 | Slovakia","value": "斯洛伐克 | Slovakia"}, 
    {"text":  "斯洛文尼亚 | Slovenia","value": "斯洛文尼亚 | Slovenia"}, 
    {"text":  "所罗门群岛 | Solomon Islands","value": "所罗门群岛 | Solomon Islands"}, 
    {"text":  "索马里 | Somalia","value": "索马里 | Somalia"}, 
    {"text":  "南非 | South Africa","value": "南非 | South Africa"}, 
    {"text":  "South Georgia and the South Sandwich Islands","value": "South Georgia and the South Sandwich Islands"}, 
    {"text":  "西班牙 | Spain","value": "西班牙 | Spain"}, 
    {"text":  "斯里兰卡 | Sri Lanka","value": "斯里兰卡 | Sri Lanka"}, 
    {"text":  "苏丹 | Sudan","value": "苏丹 | Sudan"}, 
    {"text":  "苏里南 | Suriname","value": "苏里南 | Suriname"}, 
    {"text":  "斯瓦尔巴和扬马延 | Svalbard and Jan Mayen","value": "斯瓦尔巴和扬马延 | Svalbard and Jan Mayen"}, 
    {"text":  "斯威士兰 | Swaziland","value": "斯威士兰 | Swaziland"}, 
    {"text":  "瑞典 | Sweden","value": "瑞典 | Sweden"}, 
    {"text":  "瑞士 | Switzerland","value": "瑞士 | Switzerland"}, 
    {"text":  "叙利亚‎ | Syrian Arab Republic","value": "叙利亚‎ | Syrian Arab Republic"}, 
    {"text":  "塔吉克斯坦 | Tajikistan","value": "塔吉克斯坦 | Tajikistan"}, 
    {"text":  "坦桑尼亚 | Tanzania, United Republic of","value": "坦桑尼亚 | Tanzania, United Republic of"}, 
    {"text":  "泰国 | Thailand","value": "泰国 | Thailand"}, 
    {"text":  "东帝汶 | Timor-Leste","value": "东帝汶 | Timor-Leste"}, 
    {"text":  "多哥 | Togo","value": "多哥 | Togo"}, 
    {"text":  "托克劳 | Tokelau","value": "托克劳 | Tokelau"}, 
    {"text":  "汤加 | Tonga","value": "汤加 | Tonga"}, 
    {"text":  "特立尼达和多巴哥 | Trinidad and Tobago","value": "特立尼达和多巴哥 | Trinidad and Tobago"}, 
    {"text":  "突尼斯‎ | Tunisia","value": "突尼斯‎ | Tunisia"}, 
    {"text":  "土耳其 | Turkey","value": "土耳其 | Turkey"}, 
    {"text":  "土库曼斯坦 | Turkmenistan","value": "土库曼斯坦 | Turkmenistan"}, 
    {"text":  "特克斯和凯科斯群岛 | Turks and Caicos Islands","value": "特克斯和凯科斯群岛 | Turks and Caicos Islands"}, 
    {"text":  "图瓦卢 | Tuvalu","value": "图瓦卢 | Tuvalu"}, 
    {"text":  "乌干达 | Uganda","value": "乌干达 | Uganda"}, 
    {"text":  "乌克兰 | Ukraine","value": "乌克兰 | Ukraine"}, 
    {"text":  "阿拉伯联合酋长国‎ | United Arab Emirates","value": "阿拉伯联合酋长国‎ | United Arab Emirates"}, 
    {"text":  "英国 | United Kingdom","value": "英国 | United Kingdom"}, 
    {"text":  "卡塔尔 | United States","value": "卡塔尔 | United States"}, 
    {"text":  "United States Minor Outlying Islands","value": "United States Minor Outlying Islands"}, 
    {"text":  "乌拉圭 | Uruguay","value": "乌拉圭 | Uruguay"}, 
    {"text":  "乌兹别克斯坦 | Uzbekistan","value": "乌兹别克斯坦 | Uzbekistan"}, 
    {"text":  "瓦努阿图 | Vanuatu","value": "瓦努阿图 | Vanuatu"}, 
    {"text":  "委内瑞拉 | Venezuela","value": "委内瑞拉 | Venezuela"}, 
    {"text":  "越南 | Viet Nam","value": "越南 | Viet Nam"}, 
    {"text":  "B英属维尔京群岛 | Virgin Islands, British","value": "B英属维尔京群岛 | Virgin Islands, British"}, 
    {"text":  "美属维尔京群岛 | Virgin Islands, U.S.","value": "美属维尔京群岛 | Virgin Islands, U.S."}, 
    {"text":  "瓦利斯和富图纳群岛 | Wallis and Futuna","value": "瓦利斯和富图纳群岛 | Wallis and Futuna"}, 
    {"text":  "撒哈拉沙漠西部 | Western Sahara","value": "撒哈拉沙漠西部 | Western Sahara"}, 
    {"text":  "也门 | Yemen","value": "也门 | Yemen"}, 
    {"text":  "赞比亚 | Zambia","value": "赞比亚 | Zambia"}, 
    {"text":  "津巴布韦 | Zimbabwe","value": "津巴布韦 | Zimbabwe" }]